# Site settings
title: CP's Blog
email: cpyeh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Notes for share
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cpyeh.github.io" # the base hostname & protocol for your site
github_username:  cpyeh

# Build settings
markdown: kramdown
